async(page)=>{
 const origin=new URL(page.url()).origin,errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/#/teacher');await page.getByRole('button',{name:'5問',exact:true}).click();await page.getByRole('button',{name:'まとめて判定',exact:true}).click();await page.getByRole('button',{name:'イオン名',exact:true}).click();await page.getByRole('button',{name:'クラスルームを作る',exact:true}).click();await page.locator('.code strong').waitFor();const code=await page.locator('.code strong').innerText();
 const context=await page.context().browser().newContext({viewport:{width:390,height:844}}),student=await context.newPage();student.on('pageerror',e=>errors.push(e.message));let dropped=false;
 await context.routeWebSocket('**/socket',route=>{const server=route.connectToServer();server.onMessage(message=>{try{if(!dropped&&JSON.parse(String(message)).type==='ack'){dropped=true;return;}}catch{}route.send(message);});});
 await student.goto(`${origin}/#/join/${code}`);await student.locator('#nickname').fill('まとめて確認');await student.getByRole('button',{name:'参加する',exact:true}).click();await page.getByText('まとめて確認',{exact:true}).waitFor();const provisional=await student.evaluate(code=>JSON.parse(localStorage.getItem(`ionic-lite:participant:${code}`)),code);if(!provisional.pending)throw new Error('Join credential was not saved before ack');await student.reload();await student.getByRole('button',{name:'参加を再確認',exact:true}).click();await student.locator('.nickname-editor').waitFor();const identity=await student.evaluate(code=>JSON.parse(localStorage.getItem(`ionic-lite:participant:${code}`)).participantId,code);if(identity!==provisional.participantId)throw new Error('Identity lost with join ack');
 await page.getByRole('button',{name:'まとめて確認さんを参加者から除外',exact:true}).click();await student.getByRole('button',{name:'再度エントリーする',exact:true}).click();await student.locator('#nickname').fill('再エントリー');await student.getByRole('button',{name:'参加する',exact:true}).click();await student.locator('.nickname-editor').waitFor();await student.getByRole('button',{name:'名前を変更',exact:true}).click();await student.locator('#lobby-nickname').fill('名称変更');await student.getByRole('button',{name:'保存',exact:true}).click();await page.getByText('名称変更',{exact:true}).waitFor();
 await page.locator('.settings-editor summary').click();await page.getByRole('button',{name:'3分',exact:true}).click();await page.getByRole('button',{name:'設定を保存',exact:true}).click();await student.getByText(/5問・3分・まとめて判定/).waitFor();await page.goto(origin+'/#/history');await page.getByRole('link',{name:'参加中の競技に戻る',exact:true}).first().click();await page.locator('.code strong').waitFor();if(await page.locator('.code strong').innerText()!==code)throw new Error('Wrong host recovery');await page.getByRole('button',{name:'問題を準備して開始',exact:true}).click();await student.locator('.question-navigation').waitFor();
 await student.getByRole('textbox',{name:'イオン名',exact:true}).fill('入力保持');await student.getByRole('button',{name:'次の問題',exact:true}).click();await student.getByRole('button',{name:'前の問題',exact:true}).click();await student.reload();await student.locator('.question-navigation').waitFor();if(await student.getByRole('textbox',{name:'イオン名',exact:true}).inputValue()!=='入力保持')throw new Error('Deferred draft lost');
 const active=await context.newPage();active.on('pageerror',e=>errors.push(e.message));await active.goto(student.url());await active.locator('.question-navigation').waitFor();await student.getByText(/別のタブで接続しました/).waitFor();if(!await student.getByRole('textbox',{name:'イオン名',exact:true}).isDisabled())throw new Error('Old tab can overwrite new drafts');await active.getByRole('textbox',{name:'イオン名',exact:true}).fill('新しいタブの解答');await active.reload();await active.locator('.question-navigation').waitFor();if(await active.getByRole('textbox',{name:'イオン名',exact:true}).inputValue()!=='新しいタブの解答')throw new Error('New draft overwritten');
 await page.getByRole('button',{name:'中断',exact:true}).click();await active.getByRole('textbox',{name:'イオン名',exact:true}).fill('中断直前の解答');await page.getByRole('button',{name:'中断して結果を表示',exact:true}).click();await active.locator('.results-page').waitFor();await page.locator('.results-page').waitFor();await active.getByText('あなたの解答：中断直前の解答',{exact:true}).waitFor();
 const gaps=await active.locator('.results-page .secondary-link,.results-page .primary-link').evaluateAll(nodes=>nodes.map(n=>({text:n.textContent,r:n.getBoundingClientRect().toJSON()})));if(gaps.length===2&&gaps[1].r.x<gaps[0].r.right+8)throw new Error('Results buttons touch');await context.close();
 await page.goto(origin+'/#/teacher');await page.getByRole('button',{name:'5問',exact:true}).click();await page.getByRole('button',{name:'まとめて判定',exact:true}).click();await page.getByRole('button',{name:'イオン名',exact:true}).click();await page.getByRole('button',{name:'クラスルームを作る',exact:true}).click();await page.locator('.code strong').waitFor();const submitCode=await page.locator('.code strong').innerText();const delayed=await page.context().browser().newContext({viewport:{width:320,height:844}});let holdAck=false,delayedAck=false;
 await delayed.routeWebSocket('**/socket',route=>{const server=route.connectToServer();server.onMessage(message=>{if(holdAck&&JSON.parse(String(message)).type==='ack'){delayedAck=true;setTimeout(()=>route.send(message),1200);}else route.send(message);});});const submitter=await delayed.newPage();submitter.on('pageerror',e=>errors.push(e.message));await submitter.goto(`${origin}/#/join/${submitCode}`);await submitter.locator('#nickname').fill('提出中確認');await submitter.getByRole('button',{name:'参加する',exact:true}).click();await submitter.locator('.nickname-editor').waitFor();await page.getByRole('button',{name:'問題を準備して開始',exact:true}).click();await submitter.locator('.question-navigation').waitFor();holdAck=true;await submitter.getByRole('textbox',{name:'イオン名',exact:true}).fill('提出直前の解答');await submitter.getByRole('button',{name:'全解答確認',exact:true}).click();await submitter.getByRole('button',{name:'提出する',exact:true}).click();await submitter.getByRole('heading',{name:'記録を確認しています',exact:true}).waitFor();if(await submitter.locator('.question-navigation,.review-question-list').count())throw new Error('Can navigate while submission waits for draft ack');await submitter.locator('.results-page').waitFor();await submitter.getByText('あなたの解答：提出直前の解答',{exact:true}).waitFor();if(!delayedAck)throw new Error('Draft ack was not delayed');await delayed.close();
 if(errors.length)throw new Error(JSON.stringify(errors));return {code,joinAckLossRecovered:true,reentry:true,nickname:true,settingsEdit:true,hostRecovery:true,deferredDraftReload:true,tabTakeoverLocked:true,cutoffDraftIncluded:true,resultsButtonGap:true,delayedSubmitLocksEditing:true,errors};
}
