async(page)=>{
 const origin=new URL(page.url()).origin;const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const context=await page.context().browser().newContext({viewport:{width:1280,height:844}});const normal=await context.newPage();await normal.goto('http://127.0.0.1:8789/__fixture/teacher');await normal.locator('.teacher-workspace').waitFor();
 const geometry=async(p,selector)=>p.locator(selector).evaluateAll(nodes=>nodes.filter(n=>n.getBoundingClientRect().width>0).map(n=>{const r=n.getBoundingClientRect(),s=getComputedStyle(n);return {text:n.textContent.trim(),x:Math.round(r.x*10)/10,y:Math.round(r.y*10)/10,width:Math.round(r.width*10)/10,height:Math.round(r.height*10)/10,font:s.font,padding:s.padding,gap:s.gap,borderRadius:s.borderRadius};}));
 const layouts=[];
 for(const width of [320,390,768,1280]){
  await page.setViewportSize({width,height:844});await normal.setViewportSize({width,height:844});await page.goto(origin+'/#/teacher');await normal.goto('http://127.0.0.1:8789/#/teacher');await page.locator('.teacher-workspace').waitFor();await normal.locator('.teacher-role-badge').waitFor();
  const actual=await geometry(page,'.teacher-workspace-header,.teacher-class-content .settings-summary,.teacher-class-content button'),reference=await geometry(normal,'.teacher-workspace-header,.teacher-class-content .settings-summary,.teacher-class-content button');
  if(JSON.stringify(actual)!==JSON.stringify(reference))throw new Error(JSON.stringify({width,actual,reference}));
  for(const p of [page,normal]){if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw new Error('Setup overflow '+width);}
  await page.goto(origin+'/#/');await normal.goto('http://127.0.0.1:8789/#/');await page.locator('.home-card').waitFor();await normal.locator('.home-card').waitFor();const a=await geometry(page,'.home-card header,.home-card form,.home-utility-actions'),b=await geometry(normal,'.home-card header,.home-card form,.home-utility-actions');if(JSON.stringify(a)!==JSON.stringify(b))throw new Error(JSON.stringify({width,a,b}));layouts.push({width,homeMatches:true,setupMatches:true});
 }
 await page.goto(origin+'/#/teacher');await page.getByRole('button',{name:'管理設定',exact:true}).click();await page.getByRole('button',{name:'難易度を調整',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'イオン',exact:true}).click();const row=dialog.locator('.question-profile-item').filter({hasText:'リチウムイオン'});const before=await row.getByRole('button',{name:'ややむず',exact:true}).getAttribute('aria-pressed');await row.getByRole('button',{name:'ややむず',exact:true}).click();await dialog.getByRole('button',{name:'保存',exact:true}).click();await dialog.waitFor({state:'hidden'});await page.reload();await page.getByRole('button',{name:'管理設定',exact:true}).click();await page.getByRole('button',{name:'難易度を調整',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'イオン',exact:true}).click();if(await page.getByRole('dialog').locator('.question-profile-item').filter({hasText:'リチウムイオン'}).getByRole('button',{name:'ややむず',exact:true}).getAttribute('aria-pressed')===before)throw new Error('Profile did not persist');
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});if(await page.evaluate(()=>document.querySelector('dialog').scrollWidth>innerWidth))throw new Error('Profile overflow');}
 await page.getByRole('dialog').getByRole('button',{name:'キャンセル',exact:true}).click();await page.evaluate(()=>localStorage.removeItem('ionic-lite:question-profile'));await context.close();if(errors.length)throw new Error(JSON.stringify(errors));return {layouts,profilePersistence:true,errors};
}
