async(page)=>{
 const origin=new URL(page.url()).origin;const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin);await page.locator('.home-card').waitFor();
 const layouts=[];
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});for(const route of ['#/','#/create']){await page.goto(origin+'/'+route);await page.locator(route==='#/'?'.home-card':'.teacher-workspace').waitFor();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);layouts.push({route,width,overflow});if(overflow)throw new Error(`Overflow ${route} ${width}`);}}
 await page.getByRole('button',{name:'難易度調整',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'イオン',exact:true}).click();const row=dialog.locator('.question-profile-item').filter({hasText:'リチウムイオン'});if(await row.getByRole('button',{name:'ややむず',exact:true}).getAttribute('aria-pressed')!=='false')throw new Error('Current normal profile was not migrated');await row.getByRole('button',{name:'ややむず',exact:true}).click();await dialog.getByRole('button',{name:'保存',exact:true}).click();await dialog.waitFor({state:'hidden'});await page.reload();await page.getByRole('button',{name:'難易度調整',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'イオン',exact:true}).click();if(await page.getByRole('dialog').locator('.question-profile-item').filter({hasText:'リチウムイオン'}).getByRole('button',{name:'ややむず',exact:true}).getAttribute('aria-pressed')!=='true')throw new Error('Profile did not persist');
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});if(await page.evaluate(()=>document.querySelector('dialog').scrollWidth>innerWidth))throw new Error('Profile overflow');}
 await page.getByRole('dialog').getByRole('button',{name:'キャンセル',exact:true}).click();await page.evaluate(()=>localStorage.removeItem('ionic-lite:question-profile'));
 await page.getByRole('button',{name:'5問',exact:true}).click();await page.getByRole('button',{name:'化合物',exact:true}).click();await page.getByRole('button',{name:'式 ＆ 名',exact:true}).click();await page.getByRole('button',{name:'クラスルームを作る',exact:true}).click();await page.locator('[data-testid="join-code"]').waitFor();const code=await page.locator('[data-testid="join-code"]').innerText();
 const context=await page.context().browser().newContext({viewport:{width:320,height:844}});const student=await context.newPage();student.on('pageerror',e=>errors.push(e.message));const requests=[];student.on('websocket',ws=>ws.on('framesent',f=>{try{requests.push(JSON.parse(f.payload).type);}catch{}}));await student.goto(`${origin}/#/join/${code}`);await student.getByLabel('ニックネーム').fill('通常版UI確認');await student.getByRole('button',{name:'参加する',exact:true}).click();await student.getByText('先生の開始を待っています').waitFor();await page.getByText('通常版UI確認',{exact:true}).waitFor();await page.getByRole('button',{name:'5秒後に開始',exact:true}).click();await student.locator('.play-answering').waitFor();
 const dimensions=await student.evaluate(()=>{const r=s=>document.querySelector(s).getBoundingClientRect();return {playWidth:r('.play-active').width,keyboardWidth:r('.formula-keyboard').width,firstKeyWidth:r('.letter-keys button').width,controls:Array.from(document.querySelectorAll('.immediate-actions button'),b=>({text:b.textContent,width:b.getBoundingClientRect().width,height:b.getBoundingClientRect().height})),background:getComputedStyle(document.querySelector('.play-active')).backgroundColor};});
 if(dimensions.firstKeyWidth<20||dimensions.firstKeyWidth>40||dimensions.controls.some(b=>b.height<44))throw new Error(JSON.stringify(dimensions));await student.screenshot({path:'.playwright-mcp/lite-formula-320.png',scale:'css'});
 await student.getByRole('button',{name:'パス',exact:true}).click();await student.getByRole('button',{name:'化合物名 解答中',exact:true}).waitFor();await student.getByRole('button',{name:'パス',exact:true}).click();await student.getByText('第2問 / 全5問',{exact:true}).waitFor();await student.getByRole('button',{name:'全解答確認',exact:true}).click();await student.getByRole('heading',{name:'全解答確認'}).waitFor();await student.getByRole('button',{name:'式：パス・再解答する',exact:true}).click();await student.getByRole('button',{name:'化合物名 − パス済み',exact:true}).waitFor();
 await student.getByRole('button',{name:'N',exact:true}).click();await student.getByRole('button',{name:'解答をチェック',exact:true}).click();await student.getByText('× 不正解',{exact:true}).waitFor();await student.getByRole('button',{name:'確認一覧へ戻る',exact:true}).click();await student.getByRole('button',{name:'式：再挑戦中・パス・再解答する',exact:true}).click();await student.getByRole('button',{name:'確認一覧へ戻る',exact:true}).click();
 await student.getByRole('button',{name:'続きの問題へ（第2問）',exact:true}).click();await student.getByRole('button',{name:'化合物名 解答中',exact:true}).count();
 await student.getByRole('button',{name:'パス',exact:true}).click();await student.getByRole('button',{name:'化合物名 解答中',exact:true}).waitFor();await student.getByRole('textbox',{name:'化合物名',exact:true}).fill('入力保持');await student.reload();await student.getByRole('textbox',{name:'化合物名',exact:true}).waitFor();if(await student.getByRole('textbox',{name:'化合物名',exact:true}).inputValue()!=='入力保持')throw new Error('Draft was lost');
 await page.getByRole('button',{name:'コンペを終了',exact:true}).click();await page.getByRole('button',{name:'終了する',exact:true}).click();await student.getByRole('heading',{name:'あなたの結果'}).waitFor();await context.close();
 if(errors.length)throw new Error(JSON.stringify(errors));return {code,layouts,dimensions,profileSaved:true,retryAfterWrong:true,otherFieldPassed:true,draftRestored:true,errors};
}
