import { appPath } from '../../../src/web/routing';
"use client";
import { rememberHistoryRoom } from "../../../src/features/results/history-index";
import { useEffect, useState } from "react";
import { CompetitionSettingsForm, DEFAULT_SETTINGS } from "../../../src/features/setup/CompetitionSettingsForm";
import { postJson, randomCredential, saveCredential } from "../../../src/features/play/useRoomSync";
import { ReturnHomeButton } from "../../../src/features/setup/ReturnHomeButton";
import { loadSavedNickname, saveNickname } from "../../../src/features/setup/saved-nickname";

const DRAFT_KEY = "ionic-formula-competition:mate-create";
export default function MateNewPage() {
  const [settings, setSettings] = useState(DEFAULT_SETTINGS); const [nickname, setNickname] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [pendingDraft, setPendingDraft] = useState(false);
  useEffect(() => { try { const draft = JSON.parse(localStorage.getItem(DRAFT_KEY) ?? "null"); if (draft?.settings) { setSettings(draft.settings); setNickname(draft.nickname ?? ""); setPendingDraft(true); } else setNickname(loadSavedNickname(localStorage)); } catch { setNickname(loadSavedNickname(localStorage)); } }, []);
  const create = async () => { setBusy(true); setError(""); const fresh = { requestId: crypto.randomUUID(), token: randomCredential(), creationKey: randomCredential(), nickname, settings }; let draft: typeof fresh; try { draft = JSON.parse(localStorage.getItem(DRAFT_KEY) ?? "null") ?? fresh; } catch { draft = fresh; } localStorage.setItem(DRAFT_KEY, JSON.stringify(draft)); try { const body = await postJson("/api/mate-rooms", { requestId: draft.requestId, nickname: draft.nickname, settings: draft.settings }, { token: draft.token, creationKey: draft.creationKey }); const id = body.room.id; saveCredential(id, { token: draft.token, participantId: body.participant.id }); saveNickname(localStorage, body.participant.nickname); localStorage.setItem(`ionic-formula-competition:meta:${id}`, JSON.stringify({ joinCode: body.room.joinCode, host: true })); rememberHistoryRoom(localStorage, { roomId: id, role: "participant", kind: "mate", createdAtMs: Date.now(), settings: draft.settings }); localStorage.removeItem(DRAFT_KEY); location.href = appPath(`/rooms/${encodeURIComponent(id)}`); } catch (e: any) { if (e.status && e.status < 500 && e.code !== "database_conflict") { localStorage.removeItem(DRAFT_KEY); setPendingDraft(false); } else { setSettings(draft.settings); setNickname(draft.nickname); setPendingDraft(true); } setError(e.message); setBusy(false); } };
  return <main className="page-shell"><section className="panel wide"><p className="eyebrow">MATE MATCH</p><h1>メイトマッチを作る</h1>{pendingDraft && <p className="notice">前回の作成結果を確認します。入力内容は変更できません。</p>}<label htmlFor="host-nickname">あなたのニックネーム</label><input id="host-nickname" value={nickname} maxLength={16} disabled={busy || pendingDraft} onChange={(e) => setNickname(e.target.value)}/><CompetitionSettingsForm value={settings} onChange={setSettings} disabled={busy || pendingDraft}/><button className="primary-action" disabled={busy || !nickname.trim()} onClick={create}>{busy ? "作成を確認中…" : pendingDraft ? "作成結果を再確認" : "ルームを作る"}</button><ReturnHomeButton disabled={busy}/>{error ? <p role="alert" className="error">{error}</p> : null}</section></main>;
}
