import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {StartController} from '../../src/features/lobby/start-controller';
const draft={requestId:'11111111-1111-4111-8111-111111111111',expectedRevision:5,requestedAtMs:0,protocolVersion:2,roomId:'room',ownerKey:'owner'};
function fixture(){const values=new Map<string,string>();const storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>values.set(k,v),removeItem:(k:string)=>values.delete(k)};
 const post=vi.fn().mockRejectedValue(Object.assign(new Error('timeout'),{code:'timeout'}));
 const status=vi.fn().mockResolvedValue({receipt:{preparationGeneration:1},room:{state:'PREPARING',revision:6,manifestId:'m',preparationGeneration:1}});
 const refresh=vi.fn().mockRejectedValue(new Error('refresh offline'));
 const controller=new StartController({storage,roomId:'room',ownerKey:'owner',post,status,refresh,now:()=>Date.now(),uuid:()=>draft.requestId,onChange:()=>{},visible:()=>true,online:()=>true});return {controller,storage,post,status,refresh};}
beforeEach(()=>vi.useFakeTimers());afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks();});
it('recovers committed start after timeout and never converts a failed refresh into failed start',async()=>{const f=fixture();await f.controller.begin(5,2);expect(f.controller.state.phase).toBe('confirmed');expect(f.post).toHaveBeenCalledTimes(1);expect(f.controller.pending).toBeNull();});
it('restores the same request after reload without sending a new POST',async()=>{const f=fixture();f.storage.setItem(f.controller.key,JSON.stringify(draft));await f.controller.resume();expect(f.status).toHaveBeenCalledWith(draft.requestId);expect(f.post).not.toHaveBeenCalled();expect(f.controller.state.phase).toBe('confirmed');});
// Pin the jitter so the next status check falls at 35.6s, after the old fixed 35s assertion.
it('keeps an unobserved request uncertain and only resends the exact body once',async()=>{const jitter=vi.spyOn(Math,'random').mockReturnValue(1);for(const value of [0,0,0,.4,.4,.4,.4,.4])jitter.mockReturnValueOnce(value);const f=fixture();f.status.mockResolvedValue({receipt:null,room:{state:'WAITING',revision:5}});await f.controller.begin(5,2);await vi.advanceTimersByTimeAsync(35000);expect(f.controller.state.phase).toBe('checking');await vi.advanceTimersToNextTimerAsync();expect(f.post).toHaveBeenCalledTimes(2);expect(f.post.mock.calls[0][0]).toEqual(f.post.mock.calls[1][0]);expect(f.controller.state.phase).toBe('unresolved');expect(f.controller.pending?.requestId).toBe(draft.requestId);f.controller.dispose();});
it('does not resurrect preparation when its receipt was subsequently cancelled',async()=>{const f=fixture();f.status.mockResolvedValue({receipt:{preparationGeneration:1},room:{state:'WAITING',revision:7,preparationGeneration:1}});await f.controller.begin(5,2);expect(f.controller.state.phase).toBe('rejected');expect(f.post).toHaveBeenCalledTimes(1);});
it('does not dispatch a start if the durable draft cannot be saved',async()=>{const f=fixture();f.storage.setItem=()=>{throw new Error('full')};await f.controller.begin(5,2);expect(f.post).not.toHaveBeenCalled();expect(f.controller.state.phase).toBe('rejected');});
it('ignores a late success response after a preparation cancellation was confirmed',async()=>{const f=fixture();let accept!:(value:unknown)=>void;f.post.mockImplementation(()=>new Promise(resolve=>accept=resolve));const sending=f.controller.begin(5,2);f.status.mockResolvedValue({receipt:{preparationGeneration:1},room:{state:'WAITING',revision:7}});await f.controller.check();accept({state:'PREPARING'});await sending;expect(f.controller.state.phase).toBe('rejected');expect(f.controller.pending).toBeNull();f.controller.dispose();});
it('holds the same request while the transaction has not committed yet',async()=>{const f=fixture();let accept!:(value:unknown)=>void;f.post.mockImplementation(()=>new Promise(resolve=>accept=resolve));f.status.mockResolvedValue({receipt:null,room:{state:'WAITING',revision:5}});const sending=f.controller.begin(5,2);await f.controller.check();expect(f.controller.pending?.requestId).toBe(draft.requestId);expect(f.controller.state.phase).toBe('checking');accept({state:'PREPARING'});await sending;expect(f.post).toHaveBeenCalledTimes(1);f.controller.dispose();});
it('reports stale revision only after the room remains waiting and does not automatically start with new settings',async()=>{const f=fixture();f.post.mockRejectedValue(Object.assign(new Error('設定が更新されました'),{status:409,code:'stale_room_revision'}));f.status.mockResolvedValue({receipt:null,room:{state:'WAITING',revision:6}});await f.controller.begin(5,2);expect(f.controller.state.phase).toBe('rejected');expect(f.post).toHaveBeenCalledTimes(1);f.controller.dispose();});
it('confirms another owner action without sending a replacement request',async()=>{const f=fixture();f.status.mockResolvedValue({receipt:null,room:{state:'COUNTDOWN',revision:7}});await f.controller.begin(5,2);expect(f.controller.state.message).toBe('別の操作で開始済みです。');expect(f.post).toHaveBeenCalledTimes(1);f.controller.dispose();});
it('allows a new start after a previously confirmed preparation is cancelled',async()=>{const f=fixture();await f.controller.begin(5,2);f.controller.observe('WAITING',7);expect(f.controller.state.phase).toBe('rejected');f.status.mockResolvedValue({receipt:{preparationGeneration:2},room:{state:'PREPARING',revision:8}});await f.controller.begin(7,2);expect(f.controller.state.phase).toBe('confirmed');expect(f.post).toHaveBeenCalledTimes(2);f.controller.dispose();});
it('checks current state before accepting a delayed successful POST',async()=>{const f=fixture();f.post.mockResolvedValue({state:'PREPARING'});f.status.mockResolvedValue({receipt:{preparationGeneration:1},room:{state:'WAITING',revision:7}});await f.controller.begin(5,2);expect(f.controller.state.phase).toBe('rejected');f.controller.dispose();});
